version: "3.8"

services:
  db:
    image: neo4j:5.12.0
    env_file:
      - db/credentials.env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:80
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db
    command: sh -c "/wait && npm run prod"
    environment:
      - NEO4J_URI=neo4j://db:7687
      - WAIT_HOSTS=db:7474
      - WAIT_BEFORE_HOSTS=15
      - WAIT_AFTER_HOSTS=3
