version: "3.8"

services:
  db:
    image: neo4j:5.12.0
    env_file:
      - db/credentials.env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
