openapi: 3.0.0
info:
  title: Mercury backend API
  version: 1.0.0
  description: This is an API application made with Express and documented with Swagger

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              example:
                - id: "1"
                  title: "Example Book"
                  description: "An example book description"
                  published: true
                  createdAt: "2023-01-01"

    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Books'
      responses:
        '201':
          description: The created book
          content:
            application/json:
              example:
                id: "2"
                title: "New Book"
                description: "A new book description"
                published: false
                createdAt: "2023-02-01"

components:
  schemas:
    Books:
      type: object
      required:
        - title
        - description
        - published
      properties:
        id:
          type: string
          description: The auto-generated id of the book
        title:
          type: string
          description: The title of your book
        description:
          type: string
          description: The book explanation
        published:
          type: boolean
          description: Whether you have finished reading the book
        createdAt:
          type: string
          format: date
          description: The date the book was added
